### register
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "email": "duykhanh180324@gmail.com",
    "password": "123456",
    "name": "khanh"
}

### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "emailOrPhone": "ledinhkhanh.pt4@gmail.com",
    "password": "123456"
}

### logout
DELETE  http://localhost:8080/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiMzgzNGIxNjMtMmM5ZS00ZDE2LWFmNDEtNWYyN2E0MzEwMTIxIiwiaWF0IjoxNzQ1MjIwMTYwLCJleHAiOjE3NDUyMjE5NjB9.FL6wlLnfA7TiPC_zUHn7xj7LKRQDk7duuJFW4zkaQDORw3Bh7IIo7itaMnrJvNdU-wmFpVGj8yS5T-WtFUNa8axgz2umQQvfEwPwwpYaPOk5y_tFVJTFi7Gk4GSAKqQs1rrL5CbH50941XEVsonX4ZEyvBreaDsaumhfL0GIAuHcBcq-u24gFV9wO7_DVUyNzeJrYrMG2TxHyvXLmGaazCJrenaZxjGBjnD2xGjdyRe-W2Kbo0tTuXvoIiRuWj_stcVLKT9_OidmsMEVrhLjGRY1HZBCovFb2KN3jE5g8fO6fv_t2gucZIsq2n_Rytb1nwSLixoMXd5nQuCacvn1Ow

### Logout all devices
DELETE http://localhost:8080/api/v1/users/logout-all
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiYjlmZGZiOGYtZTA5Mi00ODcxLWI2YWQtOGRiZDY5ZjdiYWU4IiwiaWF0IjoxNzQ0NDgxNzc1LCJleHAiOjE3NzYwMzkzNzV9.U_TPzBMgjGkNx6MqLCmC5u4SiM2GtdPslC73_KDsSIKumsre7K9jN-zOYvGYZLWWi5ExlTB6Df5glRhYuFUPsxYkqm48ySXS4YPbpXLgOzBpK4amijbkrGoclKwwaKpsI0a56_1YZtdbaHQseTVGzQu3_o-U4BwF-LwYIehFbppkTmozsaI6aaCgxzvtEVqrbOutxRlKJ1NoAWRUHsVyyWVTL_yDDeZotvNAsySYa2m2momRRLs0S9khH9TfFyClWbpcfGhCwS3JvGY6Ifb-2xbOfkrnFpYqHAvQgXVBzt4Upn-TbllnmQKG_FyDTdWsxZ1PrFwBirP7XvN-2YRIxg



### verify email
POST http://localhost:8080/api/v1/users/verify/email
Content-Type: application/json

{
    "email": "ledinhkhanh.pt4@gmail.com",
    "otp": "523880"
}

# router.post("/forgot-password", AuthCtrl.forgotPassword);
# router.post("/verify-otp-reset-password", AuthCtrl.verifyOTPResetPassword);
# router.post("/reset-password", AuthCtrl.resetPassword);

### forgot password
POST http://localhost:8080/api/v1/users/forgot-password
Content-Type: application/json
 
{
    "email": "khanhmh2004@gmail.com"
}

### verify otp reset password
POST http://localhost:8080/api/v1/users/verify-otp-reset-password
Content-Type: application/json
 
{
    "email": "khanhmh2004@gmail.com",
    "otp": "157992"
}


### reset password
POST http://localhost:8080/api/v1/users/reset-password
Content-Type: application/json
 
{
    "resetToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Y3NGMxOTU3MDc5N2JlMTVjNTc4MDciLCJpYXQiOjE3NDQ0NzE4NjEsImV4cCI6MTc0NDQ3MzA2MX0.hrDCQGgpoVYFbjHwtjWW0vCPQVLi9uheZ6M9CvbR2Q_hrLKX0luPIpl81ZvYlU0T1BB78XavbzUkBJAMNITmNk3yhFTfbB469xCdtGyxAicJAWHIJIINS35h4ahyChViE0HfvIIvDlQ-RiDE38R_-_QC98DOvlsTUgjtloo0QLrkXq-JGiHsEdULDUDmTLji3pvtGFDCpZukyGZdMrYR-DMUNMfq5ZBuF2T3e_2uRknmu18D16azOQPEqUxqZ9B0qo17o7zJOPEjACWAEZRdZfojt-0TRo9j6w0eM66uBJ1IOGhxR7HkIyNhGhIk790yE13XQq7x2wI0s_SDivY4bA",
    "newPassword": "180324",
    "confirmPassword": "180324"
}

### change password
POST http://localhost:8080/api/v1/users/change-password
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0IiwiaWF0IjoxNzQ0NDcyNTc2LCJleHAiOjE3NDQ0NzQzNzZ9.fERENai7giIQUI6xsSOzMC3-e3iaOdO0eb-Ij1wr3yWiSam176ikAEn42yun5AHPoUlVdoAWp5-MsL4lmpAkWuvrkwJtGEKQ3jCjMte9oToJs4zZmatnOt-jrFAwv3oRbJ49G-pxVvYdfWBa7jTzPeKDgoXvoDPBW4paxG0Iv1H8hsx7sfgc076Z0os5ewPHTf0HhZ6c7FO_gf8NMnix4fmiSuLPbtitoFLlIT-Nsn0jBO-NwvtC5uOgWjJ0k79G0Os9p4Lb6KCXpT0bMD-xFzWMCts_AMc95SHnL8BPGkLIcbuBYvUmt-TkUHbKsKYe-2mTp1vStLTjNcR_6qSdMQ 
Content-Type: application/json

{
    "oldPassword": "180324",
    "newPassword": "123456",
    "confirmPassword": "123456"
}


### refresh token
POST http://localhost:8080/api/v1/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiYjdmYTMwZWYtMDBmNC00NzcwLWI5MzMtMDNhYjY2NjA5ZmIwIiwiaWF0IjoxNzQ0NDgxOTEwLCJleHAiOjE3NzYwMzk1MTB9.J1XkZiZhFS447dd-mKmZtqmN8xsK0T4puZ655osusYdVeqNUgGQTrmjPTNK9_G3lmxt1OXuOUPVvJBF48zjsmf9YqAQDnULyITstMkPVtOLVzuS-f8ecKIQbpqKBQHY2SZflRvG4joaLl9LipX0ME0n8QgXk2A2wGQHxNBg8OXzwUZP6ohswPutY3fxJ3oO7jVNTU3GkBaIV_tQPCiTTXyotgyfNBYEo2u1gbLAug4XGcOOBLGT0PSt7cIZt06_n4wFoJHc2LInTVR73MmJMDAtirdvGMvCwwhmplJufxYLHBp3Y9PX2gYkAVeLW7ZYS0qcIH9ToJAf2B6pQzNKoXg"
}