### register
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "email": "duykhanh180324@gmail.com",
    "password": "123456",
    "name": "khanh"
}

### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "emailOrPhone": "khanhmh2004@gmail.com",
    "password": "123456"
}

### logout
DELETE  http://localhost:8080/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiZDkwZjQ5NjItOGU0Yy00NjJkLWE5M2EtNTViODFkOTcwMzAxIiwiaWF0IjoxNzQ1NjkyNTE4LCJleHAiOjE3NDU2OTQzMTh9.QSq6vSyC1l5HoniaJWDPxDTAAV_Z0s0o3WIFIiwaqrRrJoVCK6U9JRmsb3Q7Y7DayrEU0i3CRcSv62UTIxkgU3Tmu_8kAZe21iQyt36_50_yIdpYwld5luaAs5CH0MwGC2iYmaiXQwj8trGvLpb5LaAW6amIsXp72VL1Q5ZKLpf4dBHS_YB9mFNepfzaSWj3mYw2KOX2CdQxDm2CwLTw_OYF1EFcqO7xvi-sXVND0wQ-xvcBzQwIaOf5TLhqbROuwCxj9gzz83RinSmxuzuRoc5cr0hGr505mhHwF1pKg7vvHGG_GwSqTqjjywcsCegBMmPal6aQ0lVmTgp6PyRy9Q

### Logout all devices
DELETE http://localhost:8080/api/v1/users/logout-all
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiYjlmZGZiOGYtZTA5Mi00ODcxLWI2YWQtOGRiZDY5ZjdiYWU4IiwiaWF0IjoxNzQ0NDgxNzc1LCJleHAiOjE3NzYwMzkzNzV9.U_TPzBMgjGkNx6MqLCmC5u4SiM2GtdPslC73_KDsSIKumsre7K9jN-zOYvGYZLWWi5ExlTB6Df5glRhYuFUPsxYkqm48ySXS4YPbpXLgOzBpK4amijbkrGoclKwwaKpsI0a56_1YZtdbaHQseTVGzQu3_o-U4BwF-LwYIehFbppkTmozsaI6aaCgxzvtEVqrbOutxRlKJ1NoAWRUHsVyyWVTL_yDDeZotvNAsySYa2m2momRRLs0S9khH9TfFyClWbpcfGhCwS3JvGY6Ifb-2xbOfkrnFpYqHAvQgXVBzt4Upn-TbllnmQKG_FyDTdWsxZ1PrFwBirP7XvN-2YRIxg



### verify email
POST http://localhost:8080/api/v1/users/verify/email
Content-Type: application/json

{
    "email": "ledinhkhanh.pt4@gmail.com",
    "otp": "523880"
}

# router.post("/forgot-password", AuthCtrl.forgotPassword);
# router.post("/verify-otp-reset-password", AuthCtrl.verifyOTPResetPassword);
# router.post("/reset-password", AuthCtrl.resetPassword);

### forgot password
POST http://localhost:8080/api/v1/users/forgot-password
Content-Type: application/json
 
{
    "email": "khanhmh2004@gmail.com"
}

### verify otp reset password
POST http://localhost:8080/api/v1/users/verify-otp-reset-password
Content-Type: application/json
 
{
    "email": "khanhmh2004@gmail.com",
    "otp": "157992"
}


### reset password
POST http://localhost:8080/api/v1/users/reset-password
Content-Type: application/json
 
{
    "resetToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Y3NGMxOTU3MDc5N2JlMTVjNTc4MDciLCJpYXQiOjE3NDQ0NzE4NjEsImV4cCI6MTc0NDQ3MzA2MX0.hrDCQGgpoVYFbjHwtjWW0vCPQVLi9uheZ6M9CvbR2Q_hrLKX0luPIpl81ZvYlU0T1BB78XavbzUkBJAMNITmNk3yhFTfbB469xCdtGyxAicJAWHIJIINS35h4ahyChViE0HfvIIvDlQ-RiDE38R_-_QC98DOvlsTUgjtloo0QLrkXq-JGiHsEdULDUDmTLji3pvtGFDCpZukyGZdMrYR-DMUNMfq5ZBuF2T3e_2uRknmu18D16azOQPEqUxqZ9B0qo17o7zJOPEjACWAEZRdZfojt-0TRo9j6w0eM66uBJ1IOGhxR7HkIyNhGhIk790yE13XQq7x2wI0s_SDivY4bA",
    "newPassword": "180324",
    "confirmPassword": "180324"
}

### change password
POST http://localhost:8080/api/v1/users/change-password
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0IiwiaWF0IjoxNzQ0NDcyNTc2LCJleHAiOjE3NDQ0NzQzNzZ9.fERENai7giIQUI6xsSOzMC3-e3iaOdO0eb-Ij1wr3yWiSam176ikAEn42yun5AHPoUlVdoAWp5-MsL4lmpAkWuvrkwJtGEKQ3jCjMte9oToJs4zZmatnOt-jrFAwv3oRbJ49G-pxVvYdfWBa7jTzPeKDgoXvoDPBW4paxG0Iv1H8hsx7sfgc076Z0os5ewPHTf0HhZ6c7FO_gf8NMnix4fmiSuLPbtitoFLlIT-Nsn0jBO-NwvtC5uOgWjJ0k79G0Os9p4Lb6KCXpT0bMD-xFzWMCts_AMc95SHnL8BPGkLIcbuBYvUmt-TkUHbKsKYe-2mTp1vStLTjNcR_6qSdMQ 
Content-Type: application/json

{
    "oldPassword": "180324",
    "newPassword": "123456",
    "confirmPassword": "123456"
}


### refresh token
POST http://localhost:8080/api/v1/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiYjdmYTMwZWYtMDBmNC00NzcwLWI5MzMtMDNhYjY2NjA5ZmIwIiwiaWF0IjoxNzQ0NDgxOTEwLCJleHAiOjE3NzYwMzk1MTB9.J1XkZiZhFS447dd-mKmZtqmN8xsK0T4puZ655osusYdVeqNUgGQTrmjPTNK9_G3lmxt1OXuOUPVvJBF48zjsmf9YqAQDnULyITstMkPVtOLVzuS-f8ecKIQbpqKBQHY2SZflRvG4joaLl9LipX0ME0n8QgXk2A2wGQHxNBg8OXzwUZP6ohswPutY3fxJ3oO7jVNTU3GkBaIV_tQPCiTTXyotgyfNBYEo2u1gbLAug4XGcOOBLGT0PSt7cIZt06_n4wFoJHc2LInTVR73MmJMDAtirdvGMvCwwhmplJufxYLHBp3Y9PX2gYkAVeLW7ZYS0qcIH9ToJAf2B6pQzNKoXg"
}


### get message by conversation id
GET http://localhost:8080/api/v1/conversations/6801b8d45b1e152c807f0998/messages
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiODU4MDIzYTYtOTI4Yi00ZDJlLWFlNjItYzVmOThlNGI0NTc3IiwiaWF0IjoxNzQ1NDYyODgyLCJleHAiOjE3NDU0NjQ2ODJ9.OewZibRDdrKxZqD3qnVWugctljOsbuJkwnoM_XvDNMT3mgznowxm9L8Awg9QPizf_xpPoG881HyFFcOXqu5CszdQKhXn9otAfI0BdMBP6zVt5AY-bzaclX7x_idIrJQwufab8dkqc9m1_gsrGtNmcoERCQzl7-h9UYhPbjHDTTQekzVc6jANcVkbpeqOp5ZA8muHYNEQT-pHRkvyLNcbcxbbidPPWzgfLjRy73cUFu-22RneMsfoBIB9o7AszKuNQOi9pFXNYczSWnQBT5Eivawt47o-IzgyRaP98ajCaAdggtV6ULiTRxvO0G-U5IK8rC5q2G5ph316RUOfdq1QvA


### get all conversations
GET http://localhost:8080/api/v1/conversations
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc0YzE5NTcwNzk3YmUxNWM1NzgwNyIsInVzZXJuYW1lIjoiMTEyMDExOTY3MjA0NjQ5NjE1MDQ0Iiwic2Vzc2lvbklkIjoiODU4MDIzYTYtOTI4Yi00ZDJlLWFlNjItYzVmOThlNGI0NTc3IiwiaWF0IjoxNzQ1NDYyODgyLCJleHAiOjE3NDU0NjQ2ODJ9.OewZibRDdrKxZqD3qnVWugctljOsbuJkwnoM_XvDNMT3mgznowxm9L8Awg9QPizf_xpPoG881HyFFcOXqu5CszdQKhXn9otAfI0BdMBP6zVt5AY-bzaclX7x_idIrJQwufab8dkqc9m1_gsrGtNmcoERCQzl7-h9UYhPbjHDTTQekzVc6jANcVkbpeqOp5ZA8muHYNEQT-pHRkvyLNcbcxbbidPPWzgfLjRy73cUFu-22RneMsfoBIB9o7AszKuNQOi9pFXNYczSWnQBT5Eivawt47o-IzgyRaP98ajCaAdggtV6ULiTRxvO0G-U5IK8rC5q2G5ph316RUOfdq1QvA

### get all users
GET http://localhost:8080/api/v1/search/users?query=a
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDNjZmM2MzBhNTc0YWNkYzk4Y2Q3ZiIsInVzZXJuYW1lIjoiMzkzYjgxNzUtZWJlNy00NzY0LTlkODgtZjcwNWY5ZDgyMzUzIiwic2Vzc2lvbklkIjoiMjRhMTE5YmMtMmJiZS00NTBkLTgyNTktNjI3M2MxNzE5ZTEwIiwiaWF0IjoxNzQ1NjkwMzkxLCJleHAiOjE3NDU2OTIxOTF9.Uv_3lScyE0YLKP_Fev39wWY0wCwNJhTZ96K63jIFxGqGNHZ0dglNS5MIbmCl8xvQDqLbKDXlwayL3Ebeg_RP0esOJ0kXEGsxD1g75Zi0SxiUXnZP78iVISG0mxpEiSisqCtr5ZfmBRLW3qI9W7NG70lc3hRnbArUnbo9yv5RTC3kaIEDImOuVdx0vDOCzVq3mALNatSW91O4i2FzU8zFPvwEmpj-UV341lrE_M-x-gghSzQDM83UnBcG-XqFDZ9HnhOj1S3FnSIgQBG2kq-CCADHwEqyhCsqhn8djvnpwQqvKSXpq6mSDIYdlxsXm93aT-T-K2mwSnKkgEuvLfWaHw